[versions]
minSdk = "27"
compileSdk = "34"
targetSdk = "34"
androidGradlePlugin = "8.2.2"
kotlin = "1.9.10"
androidxAppCompat = "1.6.1"

[libraries]
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }